require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.nvim-tree"
require "user.treesitter"
require "user.lspconfig"
-- require "user.autopairs"
-- require "user.gitsigns"
-- require "user.bufferline"
-- require "user.lualine"
-- require "user.illuminate"
-- require "user.indentline"
-- require "user.lsp"
